# syntax=docker/dockerfile:1

FROM docker.io/golang:1.25.5-alpine
WORKDIR /workspace
RUN apk add --no-cache ca-certificates git bash
# Install dev tools (optional): air, etc.
# RUN go install github.com/air-verse/air@latest
EXPOSE 8080
CMD ["go", "run", "./cmd/resysched", "server"]
