version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Containerfile.dev
    working_dir: /workspace
    volumes:
      - .:/workspace:Z
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OPENTABLE_TOKEN=${OPENTABLE_TOKEN}
      - OPENTABLE_PERSISTED_QUERY_SHA256=${OPENTABLE_PERSISTED_QUERY_SHA256}
      - BOOKING_FIRST_NAME=${BOOKING_FIRST_NAME}
      - BOOKING_LAST_NAME=${BOOKING_LAST_NAME}
      - BOOKING_EMAIL=${BOOKING_EMAIL}
      - BOOKING_PHONE=${BOOKING_PHONE}
      - RESY_API_KEY=${RESY_API_KEY}
      - RESY_AUTH_TOKEN=${RESY_AUTH_TOKEN}
