version: "3.9"
services:
  db:
    image: docker.io/postgres:16-alpine
    environment:
      - POSTGRES_USER=resy
      - POSTGRES_PASSWORD=resy
      - POSTGRES_DB=resy
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
  app:
    build:
      context: .
      dockerfile: Containerfile.dev
    working_dir: /workspace
    depends_on:
      - db
    volumes:
      - .:/workspace:Z
    ports:
      - "8082:8080"
    env_file:
      - .env
volumes:
  pgdata: {}
